body:
  _hack: null  # an extra key with null value, which fails `utils.safe_eval`
logspout_routes:
  - id: "main"
    adapter: "logstash"
    address: "logstash.service.consul:5511"
    options:
      transport: "tcp"
      pattern: '(^\s)|(^Caused by:)'
      group_with: "previous"
      max_lines: "1024"
      cache_ttl: "10s"
